FROM node as build-frontend

ARG VITE_BRAND_HOTEL_NAME
ARG VITE_CURRENCY_SYMBOL

WORKDIR /app
COPY frontend/. /app/
COPY layer/frontend/. /app/
RUN --mount=type=cache,target=/app/.npm npm set cache /app/.npm && npm install && npm run build

FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build-frontend /app/dist/. /usr/share/nginx/html/
