version: "3.8"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data

  hotel-ms:
    build:
      context: .
      dockerfile: Dockerfile.django
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      ACCESS_TOKEN_SECONDS: "${ACCESS_TOKEN_SECONDS}"
      REFRESH_TOKEN_SECONDS: "${REFRESH_TOKEN_SECONDS}"
      DJANGO_SUPERUSER_PHONE_NUMBER: "${DJANGO_SUPERUSER_PHONE_NUMBER}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
    volumes:
      - media:/app/media
      - django-static:/app/staticfiles
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        VITE_BRAND_HOTEL_NAME: "${VITE_BRAND_HOTEL_NAME}"
        VITE_CURRENCY_SYMBOL: "${VITE_CURRENCY_SYMBOL}"
    restart: unless-stopped
    ports:
      - "${HOTEL_MS_PORT}:80"
    volumes:
      - media:/usr/share/nginx/html/media
      - django-static:/usr/share/nginx/html/static
    depends_on:
      - postgres
      - hotel-ms

volumes:
  db-data:
  media:
  django-static:
