# Generated by Django 5.1 on 2024-09-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_client_options_alter_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_description', models.TextField(verbose_name='Описание класса')),
                ('place_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость места')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free', 'Свободно'), ('unready', 'Не готово'), ('taken', 'Занято')], default='free', max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel.client'),
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_to_pay', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость проживания')),
                ('move_in_time', models.DateTimeField(verbose_name='Время въезда')),
                ('move_out_time', models.DateTimeField(verbose_name='Время выезда')),
                ('was_price_paid', models.BooleanField(default=False, verbose_name='Оплачено ли проживание')),
                ('checked_out', models.BooleanField(default=False, verbose_name='Уже выехали')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodations', to='hotel.client')),
                ('reservation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accomodation', to='hotel.reservation')),
                ('places', models.ManyToManyField(related_name='accomodations', to='hotel.place')),
            ],
            options={
                'verbose_name': 'Проживание',
                'verbose_name_plural': 'Проживания',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='places',
            field=models.ManyToManyField(related_name='reservations', to='hotel.place'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotel.classinfo')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='hotel.room'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField(verbose_name='Описание услуги')),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость услуги')),
                ('classes', models.ManyToManyField(related_name='services', to='hotel.classinfo')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_to_pay', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость услуги')),
                ('service_time', models.DateTimeField(verbose_name='Время предоставления услуги')),
                ('was_price_paid', models.BooleanField(default=False, verbose_name='Оплачена ли услуга')),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicecards', to='hotel.accomodation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicecards', to='hotel.service')),
            ],
            options={
                'verbose_name': 'Карточка услуг',
                'verbose_name_plural': 'Карточки услуг',
            },
        ),
    ]
