# Generated by Django 5.1 on 2024-11-03 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_client_user_alter_accomodation_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[+][\\d]{7,15}$')], verbose_name='Номер телефона'),
        ),
    ]
