# Generated by Django 5.1 on 2024-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('reception', 'Ресепшен'), ('service', 'Обслуживание'), ('cleaning', 'Уборка'), ('planning', 'Планировка')], default='client', max_length=16),
        ),
    ]
