# Generated by Django 5.1 on 2024-11-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_client_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('reception', 'Ресепшен'), ('service', 'Обслуживание'), ('cleaning', 'Уборка'), ('planning', 'Планировка'), ('admin', 'Администрирование')], default='client', max_length=16),
        ),
    ]
