# Generated by Django 5.1 on 2024-11-04 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_client_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[+][\\d]{7,15}$')], verbose_name='Номер телефона'),
        ),
    ]
