# Generated by Django 5.1 on 2024-11-29 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomodation',
            options={'verbose_name': 'Accomodation', 'verbose_name_plural': 'Accomodations'},
        ),
        migrations.AlterModelOptions(
            name='classinfo',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicecard',
            options={'verbose_name': 'Service card', 'verbose_name_plural': 'Service cards'},
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='checked_out',
            field=models.BooleanField(default=False, verbose_name='Did the client check out'),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='move_in_time',
            field=models.DateTimeField(verbose_name='Time of moving in'),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='move_out_time',
            field=models.DateTimeField(verbose_name='Time of moving out'),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='price_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Accomodation's price"),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='was_price_paid',
            field=models.BooleanField(default=False, verbose_name='Did the client pay'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='class_description',
            field=models.TextField(verbose_name='Class description'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='place_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price of a place'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[+][\\d]{7,15}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('reception', 'Reception'), ('service', 'Service staff'), ('cleaning', 'Cleaning staff'), ('planning', 'Plаnning staff'), ('admin', 'Admin staff')], default='client', max_length=16),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('notready', 'Not ready'), ('taken', 'Taken')], default='free', max_length=8),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='move_in_time',
            field=models.DateTimeField(verbose_name='Time of moving in'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='move_out_time',
            field=models.DateTimeField(verbose_name='Time of moving out'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(verbose_name='Service description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Service price'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='price_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Service's price"),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='service_time',
            field=models.DateTimeField(verbose_name='Time of service'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='was_price_paid',
            field=models.BooleanField(default=False, verbose_name='Did the client pay'),
        ),
    ]
