# Generated by Django 5.1 on 2024-11-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_accomodation_options_alter_classinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('reception', 'Reception staff'), ('service', 'Service staff'), ('cleaning', 'Cleaning staff'), ('planning', 'Plаnning staff'), ('admin', 'Admin staff')], default='client', max_length=16),
        ),
    ]
