# Generated by Django 5.1 on 2024-11-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_client_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='clients', verbose_name='Profile picture'),
        ),
    ]
