# Generated by Django 5.1 on 2024-12-14 16:46

import django.db.models.deletion
from django.db import migrations, models

def set_accomodation_room(apps, schema_editor):
    Accomodation = apps.get_model("hotel", "Accomodation")
    for accomodation in Accomodation.objects.all():
        accomodation.room = accomodation.places.first().room
        accomodation.save()

def set_reservation_room(apps, schema_editor):
    Reservation = apps.get_model("hotel", "Reservation")
    for reservation in Reservation.objects.all():
        reservation.room = reservation.places.first().room
        reservation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_client_picture'),
    ]

    operations = [  
        migrations.AddField(
            model_name='accomodation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accomodations', to='hotel.room'),
        ),
        migrations.RunPython(set_accomodation_room),
        migrations.AlterField(
            model_name='accomodation',
            name='room',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='accomodations', to='hotel.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel.room'),
        ),
        migrations.RunPython(set_reservation_room),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='places',
            field=models.IntegerField(default=1, verbose_name='The amount of places'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('notready', 'Not ready'), ('taken', 'Taken')], default='free', max_length=8),
        ),
        migrations.RemoveField(
            model_name='accomodation',
            name='places',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='places',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
