# Generated by Django 5.1 on 2024-12-14 19:05

from django.db import migrations, models

def set_room_number(apps, schema_editor):
    Room = apps.get_model("hotel", "Room")
    for room in Room.objects.all():
        room.room_number = room.id
        room.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_remove_accomodation_places_remove_reservation_places_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(unique=False, null=True, verbose_name='Physical room number'),
        ),
        migrations.RunPython(set_room_number),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(unique=True, null=False, verbose_name='Physical room number'),
        ),
    ]
