# Generated by Django 5.0.12 on 2025-03-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0017_alter_gallery_options_alter_galleryimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="accomodation",
            name="created_time",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Accomodation creation time"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="created_time",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Accomodation creation time"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="created_time",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Accomodation creation time"
            ),
        ),
        migrations.AddField(
            model_name="servicecard",
            name="created_time",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Accomodation creation time"
            ),
        ),
    ]
