# Generated by Django 5.0.12 on 2025-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0018_accomodation_created_time_client_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accomodation",
            name="price_to_pay",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Accomodation's price"
            ),
        ),
        migrations.AlterField(
            model_name="classinfo",
            name="place_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Price of a place"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Service price"
            ),
        ),
        migrations.AlterField(
            model_name="servicecard",
            name="price_to_pay",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Service's price"
            ),
        ),
    ]
