# Generated by Django 5.0.12 on 2025-04-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0019_alter_accomodation_price_to_pay_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=128, verbose_name="ФИО"),
        ),
    ]
