# Generated by Django 5.1 on 2024-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_classinfo_place_alter_reservation_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='price_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость проживания'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='place_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость места'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='price_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость услуги'),
        ),
    ]
